// Demo/seed profiles (README section 38).
// Inserted automatically into the database on first visit to /discover.
// Fixed UUIDs make seeding idempotent across users/sessions.

const DEMO_IDS = Array.from({ length: 24 }, (_, i) => {
  const n = String(i + 1).padStart(2, "0");
  return `00000000-0000-4000-8000-00000000${n}00`;
});

const photo = (n) => `https://i.pravatar.cc/300?img=${n}`;

function demoProfile(index, fields) {
  return {
    user_id: DEMO_IDS[index],
    name: "",
    username: "",
    bio: "",
    role: "",
    experience_level: "Intermediate",
    skills: [],
    interests: [],
    looking_for: [],
    availability: "Flexible",
    github_url: null,
    discord_username: null,
    is_demo: true,
    ...fields,
  };
}

export const DEMO_PROFILES = [
  demoProfile(0, {
    name: "Ananya Sharma",
    username: "ananyacodes",
    bio: "Frontend dev who loves shipping polished UIs fast. Looking for an ML teammate for our next hackathon.",
    role: "Frontend Developer",
    experience_level: "Intermediate",
    skills: ["React", "Next.js", "JavaScript", "Figma"],
    interests: ["AI/ML", "Web Development", "EdTech"],
    looking_for: ["ML Engineer", "Backend Developer", "Hackathon Teammate"],
    availability: "Weekends",
    github_url: "https://github.com/ananyacodes",
    discord_username: "ananya.codes",
  }),
  demoProfile(1, {
    name: "Arjun Verma",
    username: "arjunml",
    bio: "ML enthusiast. I train models on weekdays and break them on weekends. Need a frontend dev to bring my projects to life.",
    role: "ML/AI Developer",
    experience_level: "Advanced",
    skills: ["Python", "Machine Learning", "TensorFlow", "Pandas"],
    interests: ["AI/ML", "Web Development", "Open Source"],
    looking_for: ["Frontend Developer", "UI/UX"],
    availability: "Weekends",
    github_url: "https://github.com/arjunml",
    discord_username: "arjun_ml",
  }),
  demoProfile(2, {
    name: "Rahul Iyer",
    username: "rahulbuilds",
    bio: "Backend engineer. APIs, databases, and infrastructure are my comfort zone.",
    role: "Backend Developer",
    experience_level: "Intermediate",
    skills: ["Node.js", "PostgreSQL", "Docker", "SQL"],
    interests: ["SaaS", "Developer Tools", "FinTech"],
    looking_for: ["Frontend Developer", "Hackathon Teammate"],
    availability: "Weekday evenings",
    github_url: "https://github.com/rahulbuilds",
    discord_username: "rahulbuilds",
  }),
  demoProfile(3, {
    name: "Meera Nair",
    username: "meeradesigns",
    bio: "Product designer who codes a little. I turn rough ideas into clean, usable interfaces.",
    role: "UI/UX Designer",
    experience_level: "Intermediate",
    skills: ["Figma", "UI/UX", "Branding"],
    interests: ["Web Development", "HealthTech", "Gaming"],
    looking_for: ["Frontend Developer", "Project Partner"],
    availability: "Weekends",
    discord_username: "meera.design",
  }),
  demoProfile(4, {
    name: "Kabir Singh",
    username: "kabirfullstack",
    bio: "Full stack dev, 3 hackathons this year. Fast builder, always up for a weekend sprint.",
    role: "Full Stack Developer",
    experience_level: "Intermediate",
    skills: ["React", "Node.js", "MongoDB", "JavaScript"],
    interests: ["Web Development", "SaaS", "Developer Tools"],
    looking_for: ["Designer", "Hackathon Teammate"],
    availability: "Flexible",
    github_url: "https://github.com/kabirfullstack",
    discord_username: "kabir_fs",
  }),
  demoProfile(5, {
    name: "Riya Kapoor",
    username: "riyadata",
    bio: "Data scientist. I love turning messy datasets into decisions. Seeking frontend talent for AI dashboards.",
    role: "Data Scientist",
    experience_level: "Advanced",
    skills: ["Python", "SQL", "Machine Learning", "Pandas"],
    interests: ["AI/ML", "FinTech", "Climate"],
    looking_for: ["Frontend Developer", "Project Partner"],
    availability: "Weekends",
    github_url: "https://github.com/riyadata",
    discord_username: "riya_data",
  }),
  demoProfile(6, {
    name: "Dev Patel",
    username: "devopsdev",
    bio: "DevOps and cloud. If it deploys, scales and monitors, it's my kind of fun.",
    role: "DevOps",
    experience_level: "Advanced",
    skills: ["Docker", "AWS", "Kubernetes"],
    interests: ["Developer Tools", "Climate", "Open Source"],
    looking_for: ["Backend Developer", "Coding Buddy"],
    availability: "Weekday evenings",
    github_url: "https://github.com/devopsdev",
  }),
  demoProfile(7, {
    name: "Sneha Reddy",
    username: "snehacodes",
    bio: "Beginner frontend developer, learning React by building real projects. Eager to join my first hackathon team!",
    role: "Beginner Developer",
    experience_level: "Beginner",
    skills: ["JavaScript", "React", "Figma"],
    interests: ["Web Development", "EdTech", "Gaming"],
    looking_for: ["Hackathon Teammate", "Coding Buddy"],
    availability: "Weekends",
    discord_username: "sneha_codes",
  }),
  demoProfile(8, {
    name: "Vikram Joshi",
    username: "vikramjs",
    bio: "Node.js specialist. I build realtime systems and love optimizing everything.",
    role: "Backend Developer",
    experience_level: "Advanced",
    skills: ["Node.js", "MongoDB", "SQL", "Docker"],
    interests: ["Developer Tools", "SaaS", "Cybersecurity"],
    looking_for: ["Frontend Developer", "UI/UX"],
    availability: "Weekday evenings",
    github_url: "https://github.com/vikramjs",
    discord_username: "vik.js",
  }),
  demoProfile(9, {
    name: "Priya Menon",
    username: "priyapy",
    bio: "Python dev exploring ML and data engineering. Looking for a project partner for a healthtech idea.",
    role: "ML/AI Developer",
    experience_level: "Beginner",
    skills: ["Python", "Machine Learning", "SQL"],
    interests: ["HealthTech", "AI/ML", "Climate"],
    looking_for: ["Project Partner", "Frontend Developer", "Coding Buddy"],
    availability: "Flexible",
    discord_username: "priya.py",
  }),
  demoProfile(10, {
    name: "Aditya Rao",
    username: "adityamobile",
    bio: "Mobile-first builder. React Native + Firebase is my go-to stack for shipping quick MVPs.",
    role: "Mobile Developer",
    experience_level: "Intermediate",
    skills: ["JavaScript", "React", "MongoDB"],
    interests: ["Mobile", "FinTech", "Gaming"],
    looking_for: ["UI/UX", "Backend Developer"],
    availability: "Weekends",
    github_url: "https://github.com/adityamobile",
    discord_username: "aditya.mob",
  }),
  demoProfile(11, {
    name: "Isha Gupta",
    username: "ishadesigns",
    bio: "Design student obsessed with design systems. Want to team up with developers at hackathons.",
    role: "UI/UX Designer",
    experience_level: "Beginner",
    skills: ["Figma", "UI/UX", "Branding"],
    interests: ["Web Development", "EdTech", "SaaS"],
    looking_for: ["Hackathon Teammate", "Frontend Developer"],
    availability: "Flexible",
    discord_username: "isha.designs",
  }),
  demoProfile(12, {
    name: "Karthik Subramanian",
    username: "karthiksec",
    bio: "Security-focused full stack dev. CTF player. Building tools that don't leak.",
    role: "Full Stack Developer",
    experience_level: "Advanced",
    skills: ["JavaScript", "Node.js", "PostgreSQL", "Docker"],
    interests: ["Cybersecurity", "Web Development", "Open Source"],
    looking_for: ["ML Engineer", "Project Partner"],
    availability: "Weekday evenings",
    github_url: "https://github.com/karthiksec",
  }),
  demoProfile(13, {
    name: "Tanvi Desai",
    username: "tanvibuilds",
    bio: "Business + product brain. I handle pitch decks, user research and product thinking while you build.",
    role: "Product/Business",
    experience_level: "Intermediate",
    skills: ["Branding", "Figma"],
    interests: ["FinTech", "SaaS", "HealthTech"],
    looking_for: ["ML Engineer", "Frontend Developer", "Hackathon Teammate"],
    availability: "Weekends",
    discord_username: "tanvi.builds",
  }),
  demoProfile(14, {
    name: "Rohan Mehta",
    username: "rohanpytorch",
    bio: "Deep learning with PyTorch. Currently obsessed with computer vision projects.",
    role: "ML/AI Developer",
    experience_level: "Intermediate",
    skills: ["Python", "PyTorch", "Machine Learning"],
    interests: ["AI/ML", "Gaming", "Open Source"],
    looking_for: ["Frontend Developer", "Designer", "Coding Buddy"],
    availability: "Flexible",
    github_url: "https://github.com/rohanpytorch",
    discord_username: "rohan.dl",
  }),
  demoProfile(15, {
    name: "Nisha Agarwal",
    username: "nishaweb",
    bio: "Next.js fan. I care about performance scores and pixel-perfect layouts equally.",
    role: "Frontend Developer",
    experience_level: "Beginner",
    skills: ["React", "Next.js", "JavaScript"],
    interests: ["Web Development", "SaaS", "EdTech"],
    looking_for: ["Backend Developer", "Coding Buddy"],
    availability: "Weekday evenings",
    github_url: "https://github.com/nishaweb",
    discord_username: "nisha.web",
  }),
  demoProfile(16, {
    name: "Aryan Khan",
    username: "aryandevops",
    bio: "Learning cloud and containers. Beginner friendly, always down to pair on infra.",
    role: "Beginner Developer",
    experience_level: "Beginner",
    skills: ["Docker", "Python", "SQL"],
    interests: ["Developer Tools", "Climate", "Open Source"],
    looking_for: ["Coding Buddy", "Project Partner"],
    availability: "Weekends",
    discord_username: "aryan.ops",
  }),
  demoProfile(17, {
    name: "Diya Pillai",
    username: "diyadata",
    bio: "Analytics + ML. I find the story in your data and put it on screen.",
    role: "Data Scientist",
    experience_level: "Intermediate",
    skills: ["Python", "SQL", "Pandas", "Machine Learning"],
    interests: ["AI/ML", "FinTech", "HealthTech"],
    looking_for: ["Frontend Developer", "Hackathon Teammate"],
    availability: "Weekends",
    github_url: "https://github.com/diyadata",
  }),
  demoProfile(18, {
    name: "Farhan Ali",
    username: "farhanjava",
    bio: "Java backend dev. Spring Boot, microservices, and clean architecture.",
    role: "Backend Developer",
    experience_level: "Intermediate",
    skills: ["Java", "SQL", "PostgreSQL", "Docker"],
    interests: ["FinTech", "SaaS", "Cybersecurity"],
    looking_for: ["Frontend Developer", "Coding Buddy"],
    availability: "Weekday evenings",
    github_url: "https://github.com/farhanjava",
    discord_username: "farhan.java",
  }),
  demoProfile(19, {
    name: "Zara Sheikh",
    username: "zaracreates",
    bio: "Creative technologist mixing design and code for interactive experiences.",
    role: "Frontend Developer",
    experience_level: "Intermediate",
    skills: ["JavaScript", "React", "UI/UX", "Figma"],
    interests: ["Gaming", "Web Development", "Open Source"],
    looking_for: ["ML Engineer", "Backend Developer"],
    availability: "Flexible",
    github_url: "https://github.com/zaracreates",
    discord_username: "zara.create",
  }),
  demoProfile(20, {
    name: "Nikhil Chandra",
    username: "nikhilaws",
    bio: "Cloud architect-in-training. I automate boring stuff with scripts and CI/CD pipelines.",
    role: "DevOps",
    experience_level: "Intermediate",
    skills: ["AWS", "Docker", "Python", "Kubernetes"],
    interests: ["Developer Tools", "Climate", "SaaS"],
    looking_for: ["Frontend Developer", "Project Partner"],
    availability: "Weekday evenings",
    discord_username: "nikhil.cloud",
  }),
  demoProfile(21, {
    name: "Aisha Bansal",
    username: "aishaai",
    bio: "NLP researcher. LLMs, chatbots, and anything language-related excites me.",
    role: "ML/AI Developer",
    experience_level: "Advanced",
    skills: ["Python", "PyTorch", "TensorFlow", "Machine Learning"],
    interests: ["AI/ML", "EdTech", "Open Source"],
    looking_for: ["Full Stack Developer", "Designer"],
    availability: "Weekends",
    github_url: "https://github.com/aishaai",
    discord_username: "aisha.ai",
  }),
  demoProfile(22, {
    name: "Yash Kulkarni",
    username: "yashcpp",
    bio: "C++ competitive programmer building high-performance backends and tools.",
    role: "Backend Developer",
    experience_level: "Advanced",
    skills: ["C++", "Python", "SQL"],
    interests: ["Gaming", "Developer Tools", "Cybersecurity"],
    looking_for: ["UI/UX", "Frontend Developer"],
    availability: "Flexible",
    discord_username: "yash.cpp",
  }),
  demoProfile(23, {
    name: "Lakshmi Iyer",
    username: "lakshmifintech",
    bio: "FinTech builder. Payments and trading side projects, looking for a serious hackathon squad.",
    role: "Full Stack Developer",
    experience_level: "Intermediate",
    skills: ["JavaScript", "React", "Node.js", "PostgreSQL"],
    interests: ["FinTech", "SaaS", "Web Development"],
    looking_for: ["ML Engineer", "Designer", "Hackathon Teammate"],
    availability: "Full-time during hackathons",
    github_url: "https://github.com/lakshmifintech",
    discord_username: "lakshmi.ft",
  }),
];

// Inserts any demo profiles missing from the DB. Idempotent.
export async function ensureDemoProfiles() {
  const { getSupabase } = await import("./supabase.js");
  const supabase = getSupabase();

  const ids = DEMO_PROFILES.map((p) => p.user_id);
  const { data: existing, error: selectError } = await supabase
    .from("profiles")
    .select("user_id")
    .in("user_id", ids);

  if (selectError) throw selectError;

  const existingIds = new Set((existing || []).map((r) => r.user_id));
  const missing = DEMO_PROFILES.filter((p) => !existingIds.has(p.user_id));
  if (missing.length === 0) return;

  const { error: insertError } = await supabase.from("profiles").insert(missing);
  // Unique-violation means another session seeded concurrently - safe to ignore.
  if (insertError && insertError.code !== "23505") throw insertError;
}
